#!/usr/bin/env python3
"""
Conservation Analysis Script for CTCF MSA
==========================================
Takes an aligned FASTA MSA, calculates per-position conservation scores,
and generates PyMOL commands to color the structure by conservation.

Usage:
    python conservation_to_pymol.py your_msa.fasta

Output:
    - conservation_scores.txt   : per-residue scores
    - color_by_conservation.pml : paste into PyMOL OR run with:
                                  pymol -c color_by_conservation.pml
"""

import math
import sys
from collections import Counter


# 1. Read aligned FASTA

def read_fasta(filepath):
    sequences = {}
    current_id = None
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith(">"):
                current_id = line[1:].strip()
                sequences[current_id] = ""
            elif current_id:
                sequences[current_id] += line.upper()

    return sequences


# 2. Calculate Shannon entropy conservation score
# Score = 1 - normalized_entropy
# 1.0 = fully conserved, 0.0 = maximally variable

def conservation_score(column):
    """Calculate conservation score for one alignment column."""
    residues = [aa for aa in column if aa not in ("-", ".", "X")]
    if len(residues) == 0:
        return 0.0

    counts = Counter(residues)
    total = len(residues)

    entropy = 0.0
    for count in counts.values():
        p = count / total
        if p > 0:
            entropy -= p * math.log2(p)

    max_entropy = math.log2(20)
    conservation = 1.0 - (entropy / max_entropy)

    return round(conservation, 4)


# 3. Map alignment positions to reference sequence positions

def get_residue_mapping(reference_seq):
    """
    Map alignment column index -> residue number in reference sequence.
    Skips gap positions in the reference.
    Returns dict: {aln_col: residue_number}
    """
    mapping = {}
    res_num = 0
    for i, aa in enumerate(reference_seq):
        if aa not in ("-", "."):
            res_num += 1
            mapping[i] = res_num
    return mapping


# 4. Generate PyMOL script

def generate_pymol_script(residue_scores, pdb_id="5YEL", chain="A"):
    lines = []
    lines.append(f"# Conservation coloring script for {pdb_id}")
    lines.append("# Generated by conservation_to_pymol.py")
    lines.append("")
    lines.append(f"fetch {pdb_id}, async=0")
    lines.append("remove solvent")
    lines.append("remove (hetatm and not resn ZN)")
    lines.append("as cartoon")
    lines.append("")
    lines.append("# Reset all B-factors to 0")
    lines.append(f"alter chain {chain}, b=0.0")
    lines.append("")
    lines.append("# Set B-factor = conservation score for each residue")
    lines.append("# (1.0 = fully conserved, 0.0 = variable)")
    lines.append("")

    for res_num, score in sorted(residue_scores.items()):
        lines.append(f"alter (chain {chain} and resi {res_num}), b={score}")

    lines.append("")
    lines.append("# Color by conservation: white=variable, red=conserved")
    lines.append(f"spectrum b, white_yellow_orange_red, chain {chain}, minimum=0, maximum=1")
    lines.append("")
    lines.append("# Show zinc ions as spheres if present")
    lines.append("show spheres, resn ZN")
    lines.append("color gray, resn ZN")
    lines.append("")
    lines.append("# Final view")
    lines.append("zoom")
    lines.append("ray 1200, 900")
    lines.append("png ctcf_conservation.png, dpi=150")
    lines.append("")
    lines.append("print('Done! Saved ctcf_conservation.png')")

    return "\n".join(lines)


# 5. Main

def main():
    if len(sys.argv) < 2:
        print("Usage: python conservation_to_pymol.py your_msa.fasta")
        print("       Optionally: python conservation_to_pymol.py your_msa.fasta 5YEL A")
        sys.exit(1)

    fasta_file = sys.argv[1]
    pdb_id = sys.argv[2] if len(sys.argv) > 2 else "5YEL"
    chain = sys.argv[3] if len(sys.argv) > 3 else "A"

    print(f"Reading MSA from: {fasta_file}")
    sequences = read_fasta(fasta_file)

    if not sequences:
        print("ERROR: No sequences found in FASTA file.")
        sys.exit(1)

    seq_ids = list(sequences.keys())
    print(f"Found {len(seq_ids)} sequences")
    print(f"Reference (first) sequence: {seq_ids[0]}")

    lengths = set(len(s) for s in sequences.values())
    if len(lengths) > 1:
        print("ERROR: Sequences are not all the same length - MSA may not be aligned properly.")
        print(f"Lengths found: {lengths}")
        sys.exit(1)

    aln_length = list(lengths)[0]
    print(f"Alignment length: {aln_length} columns")

    ref_id = seq_ids[0]
    ref_seq = sequences[ref_id]

    col_to_resnum = get_residue_mapping(ref_seq)
    n_residues = len(col_to_resnum)
    print(f"Reference has {n_residues} residues (non-gap positions)")

    seq_list = list(sequences.values())

    residue_scores = {}
    for col_idx, res_num in col_to_resnum.items():
        column = [seq[col_idx] for seq in seq_list]
        score = conservation_score(column)
        residue_scores[res_num] = score

    with open("conservation_scores.txt", "w", encoding="utf-8") as f:
        f.write("residue_number\tconservation_score\n")
        for res_num, score in sorted(residue_scores.items()):
            f.write(f"{res_num}\t{score}\n")
    print("Wrote: conservation_scores.txt")

    pymol_script = generate_pymol_script(residue_scores, pdb_id=pdb_id, chain=chain)
    with open("color_by_conservation.pml", "w", encoding="utf-8") as f:
        f.write(pymol_script)
    print("Wrote: color_by_conservation.pml")

    scores = list(residue_scores.values())
    avg = sum(scores) / len(scores)
    hi = sum(1 for s in scores if s >= 0.8)
    lo = sum(1 for s in scores if s <= 0.2)
    print("\nConservation summary:")
    print(f"  Average score : {avg:.3f}")
    print(f"  Highly conserved (>=0.8): {hi} residues")
    print(f"  Highly variable (<=0.2) : {lo} residues")
    print("\nNext steps:")
    print("  1. Open PyMOL")
    print("  2. File > Run Script > select color_by_conservation.pml")
    print("     OR type in PyMOL: @color_by_conservation.pml")


if __name__ == "__main__":
    main()
